OPS-15679 Create a tool to remove ef-generate resources
crunchyroll/ef-open pull request #199
Opened 2020-09-09 17:50 UTC by momoneko

# Ticket
[OPS-15679](https://ellation.atlassian.net/browse/OPS-15679)

# Details
Create a tool to offboard service resources created by ef-generate

2020-09-10 23:01 UTC, vfangellation requested changes
Logic and flow of the code was very nice to read. Some changes requested.

2020-09-10 23:03 UTC, vfangellation commented on efopen/ef_degenerate.py
> +    logger.info("Deleted security group %s", sg['GroupName'])
There most likely will be an exception throw that a security group here can't be deleted because it's still being referenced from some other cloudformation stack. Unfortunately I don't know what the exception will look like in code.

2020-09-11 13:07 UTC, csalagean-ellation reviewed
Small nitpicks here and there regarding code organizing, but they are not something specific.

My only question is: Why do you use logging level `INFO` everywhere despite it could be a critical error? Like, if it couldn't delete something, probably it's nice to be categorized differently than a normal message. Also, I see that you return on every error, but in some cases, the execution should stop there in order to give time to debug and find the dependency relation on that AWS component.

2020-09-11 21:05 UTC, vfangellation commented
We might need to define a process for this tool as I only envision devops to be the people who would run this tool.

2021-11-22 12:05 UTC, momoneko commented
Closing as very old and stale.

2021-11-22 12:05 UTC, closed without merging