OPS-16055-ef-password should sanity check encrypted values
crunchyroll/ef-open pull request #212
Opened 2020-11-10 15:24 UTC by cristi-crunchyroll

# Ticket
[OPS-16055](https://ellation.atlassian.net/browse/OPS-16055)

# Details
ef-password should validate that an encrypted secret will lint cleanly when inserted into a yaml template

2020-11-16 13:26 UTC, momoneko requested changes

2020-11-16 13:26 UTC, momoneko commented on efopen/ef_password.py
> +  yaml.dump(test_dict, f, default_flow_style=False)
This check doesn't make sense to me.

What this does is serialize the secret value to yaml, which means that running yamllint is guaranteed to pass (unless the serialization goes wrong, but I can't imagine that happening, since it's basically a string).

What we should do instead is write the raw value to the file and check that.

🔴 Pinning a red dot here because this is the most important to be resolved. The rest are mostly style comments.

2020-11-16 13:26 UTC, momoneko commented on efopen/ef_password.py
> +    f = open(file, 'w')
Please read up on the `with open()` syntax. This would simplify the code quite a bit.
```
with open('filepath') as f:
```

2020-11-16 13:26 UTC, momoneko commented on efopen/ef_password.py
> +  cmd = 'yamllint -d relaxed '+file
Please favor string formatting to string addition. It is easier to read, maintain and describes the logic a lot better..

2020-11-16 13:26 UTC, momoneko commented on efopen/ef_password.py
> +    raise Exception('Msg: `{}{}`'.format(stderr, stdout))
Please do not raise top level exception types. Catching these means that you catch everything, even stuff you didn't intend to, and they don't communicate anything.

Since it's a simple script, there's really no need to implement our own, so pick one from the [Python Exception Hierarchy](https://docs.python.org/3/library/exceptions.html#exception-hierarchy). `ValueError` seems like a good candidate.

2020-11-16 13:26 UTC, momoneko commented on efopen/ef_password.py
> +  return
No need for a bare return at the end of the function.

2020-11-16 13:26 UTC, momoneko commented on efopen/ef_password.py
> +  file = "./temp.yaml"
It might be useful to use the `tempfile` module here. Would make the intent a bit clearer without the need for manual cleanup.

https://docs.python.org/3/library/tempfile.html

2020-11-18 21:38 UTC, vfangellation approved these changes
+1

2020-12-02 19:26 UTC, closed without merging

2020-12-02 19:27 UTC, rsbano commented
The Ops team has agreed to close this for the time being. We have not reached an agreement how to resolve this and will review again in the future