OPS-16137-Do not spam with 4xx CF errors in #alerts Slack channel
crunchyroll/ef-open pull request #213
Opened 2020-11-11 12:47 UTC by cristi-crunchyroll

# Ticket
[OPS-16137](https://ellation.atlassian.net/browse/OPS-16137)

# Details
Remove the 4xx cloudfront errors from ef-generate

2020-11-11 12:50 UTC, csalagean-ellation requested changes
I will not delete the condition, but I'll increase the threshold for 4xx.

2020-11-11 17:04 UTC, cristi-crunchyroll commented
I have filtered the distros considering only those that have nr_monitoring set to enabled.

2020-11-12 08:16 UTC, csalagean-ellation requested changes

2020-11-12 08:16 UTC, csalagean-ellation commented on efopen/newrelic_executor.py
> +      map_function = lambda x: (x['Id'], ', '.join(x['Aliases']['Items']))
map_function should not be in this for loop as it is not related to page.

2020-11-12 08:16 UTC, csalagean-ellation commented on efopen/newrelic_executor.py
> +      distribution_list = page['DistributionList']
`distribution_list` variable is redundant.

2020-11-12 08:16 UTC, csalagean-ellation commented on efopen/newrelic_executor.py
>        queue.extend(map(map_function, distribution_list['Items']))
As stated above, you can use `filtered_distrubtion_list` directly.

2020-11-12 08:16 UTC, csalagean-ellation commented on efopen/newrelic_executor.py
> +      return
I'll also add a log message here.

2020-11-12 11:01 UTC, momoneko requested changes

2020-11-12 14:01 UTC, cristi-crunchyroll commented on efopen/newrelic_executor.py
> +      return
Done

2020-11-12 17:14 UTC, cristi-crunchyroll commented on efopen/newrelic_executor.py
> +    pages = paginator.paginate()
Agreed

2020-11-12 17:15 UTC, cristi-crunchyroll commented on efopen/newrelic_executor.py
> +          if tag['Key'].lower() == "nr_monitoring" and tag['Value'].lower() == "enabled":
Done

2020-11-13 12:40 UTC, momoneko commented on efopen/newrelic_executor.py
> +    pages = cloudfront.get_paginator('list_distributions').paginate()
I think you have a duplicate line here. Duplicates 116
```suggestion
```

2020-11-13 12:40 UTC, momoneko commented on efopen/newrelic_executor.py
> +          if tag['Key'].lower() == "newrelic_4xx" and tag['Value'].lower() == "enabled":
I probably worded this the wrong way during the last review.

Let's keep monitoring in the tag name.
```suggestion
          if tag['Key'].lower() == "newrelic_4xx_monitoring" and tag['Value'].lower() == "enabled":
```

2020-11-13 16:24 UTC, momoneko approved these changes

2020-11-16 09:37 UTC, csalagean-ellation approved these changes

2020-11-16 19:01 UTC, merged